"""Generate supabase/seed/seed.sql from the analysed spreadsheets.

Inputs (from the analysis step in /home/claude/eleade):
  balances.json      active billing units with opening balances and suggested billing model
  doc_sessions.json  documentation file parsed into sessions
Opening balances are written as UNCONFIRMED until Jan returns the check workbook;
re-run with --confirmed <xlsx> to take his yellow-column values instead.
"""
import json, sys, datetime, argparse, uuid
sys.path.insert(0, '/home/claude/eleade')
from aliases import canon_doc, canon_coach

ap = argparse.ArgumentParser()
ap.add_argument('--confirmed', help='filled-in Eleade_Opening_Balances_Check.xlsx')
ap.add_argument('--out', default='/home/claude/eleade-app/supabase/seed/seed.sql')
args = ap.parse_args()

bal = json.load(open('/home/claude/eleade/balances.json'))
doc = json.load(open('/home/claude/eleade/doc_sessions.json'))

NS = uuid.UUID('5b1d2c1e-0000-4000-8000-00000000e1ea')
def uid(*parts):
    return str(uuid.uuid5(NS, '|'.join(parts)))

def q(v):
    if v is None:
        return 'null'
    if isinstance(v, bool):
        return 'true' if v else 'false'
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"

COACHES = [  # name, email, admin, 1:1 rate (None = Jan sets it in the app)
    ('Jani', 'info@eleadefussball.com', True, 0),
    ('Tyler', None, False, None),
    ('Paul', None, False, None),
    ('David', None, False, None),
]
FAMILY = {  # billing units that share one tab -> family name
    'Mickey Rodov + Rafi Rodov': 'Rodov',
    'Amber Nedalkov + Riley Nedalkov': 'Nedalkov',
    'Mayllone Sasi Kumar + Vaylone Sasi Kumar': 'Sasi Kumar',
}

# ---- confirmed values from Jan's workbook (optional) ----
confirmed = {}
if args.confirmed:
    import openpyxl
    ws = openpyxl.load_workbook(args.confirmed, data_only=True)['Opening balances']
    hdr = [c.value for c in ws[1]]
    col = {h: i for i, h in enumerate(hdr)}
    for row in ws.iter_rows(min_row=2, values_only=True):
        if not row[0] or row[0] == 'Totals':
            continue
        confirmed[row[0]] = {
            'model': row[col['BILLING MODEL']], 's': row[col['CONFIRMED sessions left']],
            'a': row[col['CONFIRMED analyses left']], 'pkg': row[col['Package type']], 'note': row[col['Your notes']],
        }

out = ['-- Generated by scripts/build_seed.py on %s. Do not edit by hand.' % datetime.date.today().isoformat(),
       'begin;']

for name, email, admin, rate in COACHES:
    cid = uid('coach', name)
    out.append('insert into public.coaches (id, name, email, is_admin) values (%s, %s, %s, %s);'
               % (q(cid), q(name), q(email), q(admin)))
    out.append('insert into public.coach_rates (coach_id, one_to_one) values (%s, %s);' % (q(cid), q(rate)))

players = {}   # name -> id
active = set()
for b in bal:
    unit = b['player']
    members = unit.split(' + ')
    fam = FAMILY.get(unit)
    c = confirmed.get(unit, {})
    model = (c.get('model') or b['suggested_model'] or 'Package')
    model = 'pay_per_session' if str(model).lower().startswith('pay') else 'package'
    coach = canon_coach(b['main_coach'])
    for i, m in enumerate(members):
        pid = uid('player', m)
        players[m] = pid
        active.add(m)
        out.append('insert into public.players (id, name, family, billing_model, main_coach_id, active, opening_confirmed, profile_notes) '
                   'values (%s, %s, %s, %s, %s, true, %s, %s);'
                   % (q(pid), q(m), q(fam), q(model), q(uid('coach', coach)) if coach else 'null',
                      q(bool(c)), q(c.get('note'))))
    if model != 'package':
        continue
    s = c.get('s') if c else b['sessions_remaining']
    a = c.get('a') if c else b['analysis_remaining']
    if s is None and a is None:
        continue
    reason = ('Opening balance confirmed by Jan' if c else
              'Opening balance from Abrechnung (unconfirmed)')
    if c.get('pkg'):
        reason += ' · ' + str(c['pkg'])
    out.append("insert into public.credit_ledger (player_id, kind, sessions_delta, analyses_delta, reason, effective_date) "
               "values (%s, 'opening', %s, %s, %s, %s);"
               % (q(players[members[0]]), q(float(s or 0)), q(float(a or 0)), q(reason), q(datetime.date.today().isoformat())))

# ---- 2026 history from the documentation file (imported: never touches credits or pay) ----
FORMAT = {'fußball 1:1': '1:1', '1:1': '1:1', 'fußball 2:1': '2:1', '2:1': '2:1', '2:1  trailsession': '2:1',
          'video analysis': 'analysis', 'talent id testing': 'testing'}
known_coaches = {c[0] for c in COACHES}
n_hist = skipped = 0
for srec in doc['sessions']:
    if '_problem' in srec or not srec['date'].startswith('2026'):
        continue
    if srec['date'] > '2026-10-04':
        skipped += 1
        continue
    name = canon_doc(srec['player_tab'])
    if name not in players:
        pid = uid('player', name)
        players[name] = pid
        out.append('insert into public.players (id, name, active) values (%s, %s, false);' % (q(pid), q(name)))
    coach = canon_coach(srec['coach'])
    if coach == 'David+Jani':
        coach = 'David'
    if coach not in known_coaches:
        coach = 'Jani'  # Luca, Cem, Jack and blanks: keep the note, attribute to admin for history only
        note_coach = canon_coach(srec['coach']) or 'unknown'
    else:
        note_coach = None
    fmt = FORMAT.get((srec['type'] or '').strip().lower(), '1:1')
    sid = uid('hist', srec['player_tab'], str(srec['_row']))
    topic = ' / '.join(x for x in (srec['warmup'], srec['topic1'], srec['topic2']) if x)
    obs = ' / '.join(x for x in (srec['coaching_points'], srec['fb_main'], srec['fb_warmup']) if x)
    imp = srec['next_ideas']
    comment = ' / '.join(x for x in ((('Coach in old file: ' + note_coach) if note_coach else None), srec['comment']) if x)
    if comment:
        obs = (obs + ' / ' if obs else '') + comment
    out.append("insert into public.sessions (id, session_date, coach_id, format, outcome, location, topic, observations, improve, imported) "
               "values (%s, %s, %s, %s, 'attended', %s, %s, %s, %s, true);"
               % (q(sid), q(srec['date']), q(uid('coach', coach)), q(fmt), q(srec['location']),
                  q(topic or None), q(obs or None), q(imp)))
    out.append('insert into public.session_players (session_id, player_id) values (%s, %s);' % (q(sid), q(players[name])))
    n_hist += 1

out.append('commit;')
import os
os.makedirs(os.path.dirname(args.out), exist_ok=True)
open(args.out, 'w').write('\n'.join(out) + '\n')

# Also write paste-sized parts for the Supabase SQL editor: part 1 = team, players, credits;
# parts 2+ = documentation history (each session insert is followed by its player link).
body = out[2:-1]
split = next(i for i, l in enumerate(body) if l.startswith('insert into public.sessions'))
core, hist = body[:split], body[split:]
parts = [core] + [hist[i:i + 900] for i in range(0, len(hist), 900)]
d = os.path.dirname(args.out)
for f in os.listdir(d):
    if f.startswith('part'):
        os.remove(os.path.join(d, f))
for n, chunk in enumerate(parts, 1):
    open(os.path.join(d, 'part%d.sql' % n), 'w').write(out[0] + '\nbegin;\n' + '\n'.join(chunk) + '\ncommit;\n')
print('parts', len(parts))
print('players', len(players), 'active', len(active), 'history sessions', n_hist, 'skipped future-dated', skipped,
      'confirmed rows used', len(confirmed))
