db-uri = "postgres://authenticator@/eleade?host=/var/tmp&port=5433"
db-schemas = "public"
db-anon-role = "anon"
jwt-secret = "local-dev-secret-local-dev-secret-0123456789"
server-port = 3001
db-pool = 5
